### ISSUE TITLE
1. get familiar with git command line

### ISSUE THREAD

**Issue by LTS42** [brianjo94/HospitalEmergeNameEntry#2]
using git command line,
branch off `main` and create a file called dog.txt which has a single word `cash` and open a pull request

**Comment by LTS42** [comment]
using git command line,
branch off `main` and create a file called dog.txt which has a single word `cash` and open a pull request

**Comment by xraycodes** [comment]
git init
git branch sidebranch
git checkout sidebranch 
touch dog.txt
open dog.txt 

git add dog.txt
git commit -m 'uploading dog.txt on branch'
git checkout main

git remote add origin (GitHub Link)
git push -u origin main

**Comment by LTS42** [comment]
actually do it against this repository

**Comment by brianjo94** [comment]
![image](https://user-images.githubusercontent.com/84826985/204588132-73a73f08-bd92-407f-b307-c5381e2546ec.png)

**Comment by xraycodes** [comment]
![image](https://user-images.githubusercontent.com/84826985/204590324-ab53a434-9241-498a-a505-0051bbc198b9.png)

I cant upload it remotely to this depository as seen in the last error message. I think the reason was because I made this repository from GitHub itself and not locally first meaning I don't have the actual file locally.. I tried using cloning but same result.. People were saying to do it using force(-f) but I also read that that's not good practice and can screw up badly in a large scale projects.

**Comment by LTS42** [comment]
you are trying to push to `main`.
`main` cannot accept any `push` (we don't call it `upload` let's call it `push`)
try to `push` to another branch, not `main`

Have you created and registered `ssh keys?`

**Comment by xraycodes** [comment]
pushed a branch that I created locally called Sidebranch and was able to push. Is this correct?

**Comment by LTS42** [comment]
yes.
now go back to the original issue and do it again for good measures.

pay attention to the task
